# Generated by Django 4.2.7 on 2026-01-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Leadership', 'Leadership'), ('Innovation', 'Innovation'), ('Community', 'Community'), ('Science Fair', 'Science Fair'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Other', 'Other')], help_text='Activity category', max_length=50),
        ),
    ]
