# Generated by Django 4.2.7 on 2025-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0002_newadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newadmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Under Review', 'Under Review'), ('Waitlisted', 'Waitlisted'), ('Enrolled', 'Enrolled')], default='Pending', max_length=20),
        ),
    ]
