# Generated by Django 4.2.7 on 2026-01-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0002_alter_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(default='Active', help_text='Activity status', max_length=50),
        ),
    ]
