# Generated by Django 4.2.7 on 2025-12-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0002_rename_hire_date_teacher_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newadmission',
            name='admission_id',
            field=models.CharField(blank=True, help_text='Admission ID reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newadmission',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Admission fees', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='newadmission',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade/Level of the student', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newadmission',
            name='student_id',
            field=models.CharField(blank=True, help_text='Student ID (can be provided during admission)', max_length=100, null=True),
        ),
    ]
