# Generated by Django 4.2.7 on 2025-12-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0003_newadmission_admission_id_newadmission_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newadmission',
            name='admission_id',
        ),
        migrations.RemoveField(
            model_name='newadmission',
            name='school',
        ),
        migrations.RemoveField(
            model_name='newadmission',
            name='user',
        ),
    ]
