# Generated by Django 4.2.7 on 2026-01-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0004_remove_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, default='Other', help_text='Activity type', max_length=50, null=True),
        ),
    ]
