# Generated by Django 4.2.7 on 2025-12-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0004_remove_newadmission_admission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newadmission',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password created by user', max_length=128, null=True),
        ),
    ]
