# Generated by Django 4.2.7 on 2026-01-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0005_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
    ]
