# Generated by Django 4.2.7 on 2026-01-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0006_remove_activity_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
