# Generated by Django 4.2.7 on 2026-01-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0007_alter_event_options_remove_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2025-01-01', help_text='Event date', null=True),
        ),
    ]
