# Generated by Django 4.2.7 on 2026-01-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0008_alter_event_options_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='photo_id',
        ),
    ]
