# Generated by Django 4.2.7 on 2026-01-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0009_remove_galleryimage_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='photo_id',
            field=models.CharField(blank=True, help_text='Reference to Gallery Photo ID', max_length=100, null=True),
        ),
    ]
