# Generated by Django 4.2.7 on 2026-01-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0010_galleryimage_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='uploaded_at',
        ),
    ]
