# Generated by Django 4.2.7 on 2025-12-16 05:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        ('management_admin', '0026_add_receipt_number_to_payment_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bus_number', models.CharField(help_text='Unique bus number/identifier', max_length=100, unique=True)),
                ('bus_type', models.CharField(choices=[('Mini Bus', 'Mini Bus'), ('Standard Bus', 'Standard Bus'), ('Large Bus', 'Large Bus'), ('AC Bus', 'AC Bus')], help_text='Type of bus', max_length=50)),
                ('capacity', models.IntegerField(help_text='Passenger capacity of the bus', validators=[django.core.validators.MinValueValidator(1)])),
                ('registration_number', models.CharField(help_text='Vehicle registration number', max_length=100, unique=True)),
                ('driver_name', models.CharField(help_text='Full name of the driver', max_length=255)),
                ('driver_phone', models.CharField(help_text='Driver contact phone number', max_length=20)),
                ('driver_license', models.CharField(help_text='Driver license number', max_length=100)),
                ('driver_experience', models.IntegerField(blank=True, help_text='Years of driving experience', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('route_name', models.CharField(help_text='Name of the bus route', max_length=255)),
                ('route_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Route distance in kilometers', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('route_description', models.TextField(blank=True, help_text='Detailed description of the route')),
                ('morning_start_time', models.TimeField(help_text='Morning pickup start time')),
                ('morning_end_time', models.TimeField(help_text='Morning pickup end time')),
                ('afternoon_start_time', models.TimeField(help_text='Afternoon drop-off start time')),
                ('afternoon_end_time', models.TimeField(help_text='Afternoon drop-off end time')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about the bus')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bus is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(help_text='School that owns this bus', on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='super_admin.school')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'db_table': 'buses',
                'ordering': ['bus_number', '-created_at'],
                'indexes': [models.Index(fields=['bus_number'], name='buses_bus_num_f1491d_idx'), models.Index(fields=['school', 'is_active'], name='buses_school__70f1b8_idx')],
            },
        ),
    ]
