# Generated by Django 4.2.7 on 2025-12-16 06:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0027_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('stop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(help_text='Name of the bus stop', max_length=255)),
                ('stop_time', models.TimeField(help_text='Time when bus arrives at this stop')),
                ('route_type', models.CharField(choices=[('morning', 'Morning Route (Pick-up)'), ('afternoon', 'Afternoon Route (Drop-off)')], help_text='Type of route: morning (pick-up) or afternoon (drop-off)', max_length=20)),
                ('stop_order', models.IntegerField(help_text='Order of stop in the route (1, 2, 3, ...)', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(help_text='Bus associated with this stop', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='management_admin.bus')),
            ],
            options={
                'verbose_name': 'Bus Stop',
                'verbose_name_plural': 'Bus Stops',
                'db_table': 'bus_stops',
                'ordering': ['bus', 'route_type', 'stop_order'],
            },
        ),
        migrations.CreateModel(
            name='BusStopStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id_string', models.CharField(blank=True, help_text='Student ID as string (cached from student table)', max_length=100)),
                ('student_name', models.CharField(blank=True, help_text='Student name (cached from student table)', max_length=255)),
                ('student_class', models.CharField(blank=True, help_text='Student class (cached from student table)', max_length=50)),
                ('student_grade', models.CharField(blank=True, help_text='Student grade (cached from student table)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop', models.ForeignKey(help_text='Bus stop where student boards/alights', on_delete=django.db.models.deletion.CASCADE, related_name='stop_students', to='management_admin.busstop')),
                ('student', models.ForeignKey(help_text='Student using this bus stop', on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='management_admin.student')),
            ],
            options={
                'verbose_name': 'Bus Stop Student',
                'verbose_name_plural': 'Bus Stop Students',
                'db_table': 'bus_stop_students',
                'ordering': ['stop', 'student_name'],
                'indexes': [models.Index(fields=['stop'], name='bus_stop_st_stop_id_f3450d_idx'), models.Index(fields=['student'], name='bus_stop_st_student_dd5ef8_idx')],
                'unique_together': {('stop', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=models.Index(fields=['bus', 'route_type'], name='bus_stops_bus_id_095242_idx'),
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=models.Index(fields=['bus', 'route_type', 'stop_order'], name='bus_stops_bus_id_53e13a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='busstop',
            unique_together={('bus', 'route_type', 'stop_order')},
        ),
    ]
