# Generated by Django 4.2.7 on 2025-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0028_busstop_busstopstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='busstopstudent',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examination_management',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newadmission',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
    ]
