# Generated by Django 4.2.7 on 2025-12-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0029_busstop_school_id_busstopstudent_school_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='designation',
        ),
        migrations.AlterField(
            model_name='busstop',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='busstopstudent',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='examination_management',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newadmission',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
    ]
