# Generated by Django 4.2.7 on 2025-12-17 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0030_remove_designation_from_teacher'),
    ]

    operations = [
        # Create File model
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Profile photo (2-4MB, jpg/jpeg/png/gif only)', upload_to='profile_photos/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='main_login.user')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'files',
            },
        ),
        # Add school_id to NewAdmission (skip if already exists)
        migrations.RunSQL(
            sql="ALTER TABLE new_admissions ADD COLUMN IF NOT EXISTS school_id VARCHAR(100); CREATE INDEX IF NOT EXISTS new_admissions_school_id_idx ON new_admissions(school_id);",
            reverse_sql="DROP INDEX IF EXISTS new_admissions_school_id_idx; ALTER TABLE new_admissions DROP COLUMN IF EXISTS school_id;",
        ),
        # Add school_id to Examination_management (skip if already exists)
        migrations.RunSQL(
            sql="ALTER TABLE examination_management ADD COLUMN IF NOT EXISTS school_id VARCHAR(100); CREATE INDEX IF NOT EXISTS examination_management_school_id_idx ON examination_management(school_id);",
            reverse_sql="DROP INDEX IF EXISTS examination_management_school_id_idx; ALTER TABLE examination_management DROP COLUMN IF EXISTS school_id;",
        ),
        # Convert existing profile_photo_id to ForeignKey for Teacher
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                -- Check if profile_photo_id exists and is UUID, convert to ForeignKey
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='teachers' AND column_name='profile_photo_id') THEN
                    -- Column exists, ensure it's the right type for ForeignKey
                    ALTER TABLE teachers ALTER COLUMN profile_photo_id TYPE UUID USING profile_photo_id::UUID;
                ELSE
                    -- Column doesn't exist, add it
                    ALTER TABLE teachers ADD COLUMN profile_photo_id UUID REFERENCES files(file_id) ON DELETE SET NULL;
                END IF;
                CREATE INDEX IF NOT EXISTS teachers_profile_photo_id_idx ON teachers(profile_photo_id);
            END $$;
            """,
            reverse_sql="ALTER TABLE teachers DROP COLUMN IF EXISTS profile_photo_id;",
        ),
        # Add profile_photo to Student (create new column)
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='students' AND column_name='profile_photo_id') THEN
                    ALTER TABLE students ADD COLUMN profile_photo_id UUID REFERENCES files(file_id) ON DELETE SET NULL;
                    CREATE INDEX IF NOT EXISTS students_profile_photo_id_idx ON students(profile_photo_id);
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE students DROP COLUMN IF EXISTS profile_photo_id;",
        ),
    ]
