# Generated by Django 4.2.7 on 2025-12-19 05:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import management_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0010_alter_school_school_id'),
        ('management_admin', '0036_update_busstopstudent_field_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='busstopstudent',
            options={'ordering': ['bus_stop', 'student_name'], 'verbose_name': 'Bus Stop Student', 'verbose_name_plural': 'Bus Stop Students'},
        ),
        migrations.RemoveIndex(
            model_name='bus',
            name='buses_bus_num_f1491d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bus',
            name='buses_school__70f1b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='busstop',
            name='bus_stops_bus_id_095242_idx',
        ),
        migrations.RemoveIndex(
            model_name='busstop',
            name='bus_stops_bus_id_53e13a_idx',
        ),
        migrations.RemoveIndex(
            model_name='busstopstudent',
            name='bus_stop_st_stop_id_f3450d_idx',
        ),
        migrations.RemoveIndex(
            model_name='busstopstudent',
            name='bus_stop_st_student_dd5ef8_idx',
        ),
        # Handle unique_together constraint separately since field was renamed from 'stop' to 'bus_stop' in migration 0036
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Drop the old unique constraint on (stop_id, student_id) if it exists
                migrations.RunSQL(
                    sql="ALTER TABLE bus_stop_students DROP CONSTRAINT IF EXISTS bus_stop_students_stop_id_student_id_key;",
                    reverse_sql="-- Cannot reverse constraint drop",
                ),
                # Add new unique constraint on (bus_stop_id, student_id) - but wait, the column is still stop_id
                # Actually, since db_column='stop_id', the constraint should work with the existing column
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='busstopstudent',
                    unique_together={('bus_stop', 'student')},
                ),
            ],
        ),
        # Remove school_id from payment_history if it exists
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE payment_history DROP COLUMN IF EXISTS school_id;",
                    reverse_sql="-- Cannot reverse column drop",
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='paymenthistory',
                    name='school_id',
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='profile_photo_id',
        ),
        # Add fields to busstop if they don't exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$ 
                        BEGIN
                            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bus_stops' AND column_name='latitude') THEN
                                ALTER TABLE bus_stops ADD COLUMN latitude NUMERIC(9,6);
                            END IF;
                            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bus_stops' AND column_name='longitude') THEN
                                ALTER TABLE bus_stops ADD COLUMN longitude NUMERIC(9,6);
                            END IF;
                            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bus_stops' AND column_name='stop_address') THEN
                                ALTER TABLE bus_stops ADD COLUMN stop_address TEXT;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='busstop',
                    name='latitude',
                    field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
                ),
                migrations.AddField(
                    model_name='busstop',
                    name='longitude',
                    field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
                ),
                migrations.AddField(
                    model_name='busstop',
                    name='stop_address',
                    field=models.TextField(blank=True, help_text='Address of the bus stop'),
                ),
            ],
        ),
        # Add fields to busstopstudent if they don't exist
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$ 
                        BEGIN
                            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bus_stop_students' AND column_name='dropoff_time') THEN
                                ALTER TABLE bus_stop_students ADD COLUMN dropoff_time TIME;
                            END IF;
                            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='bus_stop_students' AND column_name='pickup_time') THEN
                                ALTER TABLE bus_stop_students ADD COLUMN pickup_time TIME;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='busstopstudent',
                    name='dropoff_time',
                    field=models.TimeField(blank=True, help_text='Dropoff time for this student at this stop', null=True),
                ),
                migrations.AddField(
                    model_name='busstopstudent',
                    name='pickup_time',
                    field=models.TimeField(blank=True, help_text='Pickup time for this student at this stop', null=True),
                ),
            ],
        ),
        # Add profile_photo fields if they don't exist (they're ForeignKeys, so we need to check if the column exists)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$ 
                        BEGIN
                            -- Student profile_photo_id column already exists, no need to add
                            -- Teacher profile_photo_id column already exists, no need to add
                            -- These are just ForeignKey fields pointing to existing columns
                        END $$;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='student',
                    name='profile_photo',
                    field=models.ForeignKey(blank=True, db_column='profile_photo_id', help_text='Profile photo file (2-4MB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='management_admin.file'),
                ),
                migrations.AddField(
                    model_name='teacher',
                    name='profile_photo',
                    field=models.ForeignKey(blank=True, db_column='profile_photo_id', help_text='Profile photo file (2-4MB)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to='management_admin.file'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(help_text='Unique bus number/identifier (Primary Key)', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='super_admin.school'),
        ),
        migrations.AlterField(
            model_name='busstopstudent',
            name='bus_stop',
            field=models.ForeignKey(db_column='stop_id', on_delete=django.db.models.deletion.CASCADE, related_name='stop_students', to='management_admin.busstop'),
        ),
        migrations.AlterField(
            model_name='busstopstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_stops', to='management_admin.student'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='Profile photo (2-4MB, jpg/jpeg/png/gif only)', upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), management_admin.models.validate_file_size]),
        ),
    ]
