# Generated by Django 4.2.7 on 2025-12-19
# Manually updated to handle UUID to formatted string conversion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0038_fix_bus_stop_students_stop_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Step 1: Drop foreign key constraint
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bus_stop_students 
                        DROP CONSTRAINT IF EXISTS bus_stop_students_stop_id_fkey CASCADE;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
                # Step 2: Clear bus_stop_students table (since we're changing the primary key format)
                migrations.RunSQL(
                    sql="""
                        TRUNCATE TABLE bus_stop_students CASCADE;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
                # Step 3: Change stop_id column type in bus_stop_students to VARCHAR
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bus_stop_students 
                        ALTER COLUMN stop_id TYPE VARCHAR(255) USING stop_id::text;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
                # Step 4: Drop primary key constraint on bus_stops
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bus_stops DROP CONSTRAINT IF EXISTS bus_stops_pkey CASCADE;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
                # Step 5: Add temporary stop_id_new column
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bus_stops 
                        ADD COLUMN stop_id_new VARCHAR(255);
                    """,
                    reverse_sql="ALTER TABLE bus_stops DROP COLUMN IF EXISTS stop_id_new;",
                ),
                # Step 6: Populate stop_id_new with formatted values
                migrations.RunSQL(
                    sql="""
                        UPDATE bus_stops 
                        SET stop_id_new = bus_number || '_' || LEFT(route_type, 3) || '_' || stop_order::text;
                    """,
                    reverse_sql="UPDATE bus_stops SET stop_id_new = NULL;",
                ),
                # Step 7: Drop old stop_id column
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bus_stops DROP COLUMN IF EXISTS stop_id;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
                # Step 8: Rename stop_id_new to stop_id and make it primary key
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bus_stops RENAME COLUMN stop_id_new TO stop_id;
                        ALTER TABLE bus_stops ALTER COLUMN stop_id SET NOT NULL;
                        ALTER TABLE bus_stops ADD PRIMARY KEY (stop_id);
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
                # Step 9: Recreate foreign key constraint
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE bus_stop_students 
                        ADD CONSTRAINT bus_stop_students_stop_id_fkey 
                        FOREIGN KEY (stop_id) REFERENCES bus_stops(stop_id) ON DELETE CASCADE;
                    """,
                    reverse_sql="-- Cannot reverse",
                ),
            ],
            state_operations=[
                # Update model state
                migrations.AlterField(
                    model_name='busstop',
                    name='stop_id',
                    field=models.CharField(editable=False, help_text='Stop ID in format: busnumber_routeprefix_stopnumber', max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
