# Generated by Django 4.2.7 on 2025-12-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0039_change_busstop_id_to_formatted_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='route_description',
        ),
        migrations.AddField(
            model_name='bus',
            name='end_location',
            field=models.CharField(blank=True, help_text='Ending location of the route', max_length=255),
        ),
        migrations.AddField(
            model_name='bus',
            name='start_location',
            field=models.CharField(blank=True, help_text='Starting location of the route', max_length=255),
        ),
    ]
