# Generated by Django 4.2.7 on 2025-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0040_replace_route_description_with_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='busstopstudent',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examination_management',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
    ]
