# Generated by Django 4.2.7 on 2025-12-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0041_busstop_school_name_busstopstudent_school_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_class',
            field=models.CharField(blank=True, help_text='Class name for class teacher assignment (e.g., Grade 9, 10)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_grade',
            field=models.CharField(blank=True, help_text='Grade level for class teacher assignment (e.g., A, B, C, D)', max_length=10, null=True),
        ),
    ]
