# Generated by Django 4.2.7 on 2025-12-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0042_add_class_teacher_class_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newadmission',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('Other', 'Other')], default='General', max_length=20),
        ),
    ]
