# Generated by Django 4.2.7 on 2025-12-24 12:40

from django.db import migrations, models


def convert_profile_photo_to_charfield(apps, schema_editor):
    """Convert profile_photo_id (UUID ForeignKey) to profile_photo (VARCHAR)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # For teachers table
        # Check if profile_photo_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='teachers' AND column_name='profile_photo_id'
        """)
        if cursor.fetchone():
            # Drop foreign key constraint and index if they exist
            try:
                cursor.execute("ALTER TABLE teachers DROP CONSTRAINT IF EXISTS teachers_profile_photo_id_fkey")
            except Exception:
                pass
            try:
                cursor.execute("DROP INDEX IF EXISTS teachers_profile_photo_id_idx")
            except Exception:
                pass
            
            # Drop old column
            cursor.execute("ALTER TABLE teachers DROP COLUMN profile_photo_id")
        
        # Add new column if it doesn't exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='teachers' AND column_name='profile_photo'
        """)
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE teachers ADD COLUMN profile_photo VARCHAR(100)")
        
        # For students table
        # Check if profile_photo_id column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='students' AND column_name='profile_photo_id'
        """)
        if cursor.fetchone():
            # Drop foreign key constraint and index if they exist
            try:
                cursor.execute("ALTER TABLE students DROP CONSTRAINT IF EXISTS students_profile_photo_id_fkey")
            except Exception:
                pass
            try:
                cursor.execute("DROP INDEX IF EXISTS students_profile_photo_id_idx")
            except Exception:
                pass
            
            # Drop old column
            cursor.execute("ALTER TABLE students DROP COLUMN profile_photo_id")
        
        # Add new column if it doesn't exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='students' AND column_name='profile_photo'
        """)
        if not cursor.fetchone():
            cursor.execute("ALTER TABLE students ADD COLUMN profile_photo VARCHAR(100)")


def reverse_convert_profile_photo(apps, schema_editor):
    """Reverse migration - convert back to ForeignKey"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # For teachers table - convert back to UUID ForeignKey
        cursor.execute("ALTER TABLE teachers DROP COLUMN IF EXISTS profile_photo")
        cursor.execute("ALTER TABLE teachers ADD COLUMN IF NOT EXISTS profile_photo_id UUID REFERENCES files(file_id) ON DELETE SET NULL")
        cursor.execute("CREATE INDEX IF NOT EXISTS teachers_profile_photo_id_idx ON teachers(profile_photo_id)")
        
        # For students table - convert back to UUID ForeignKey
        cursor.execute("ALTER TABLE students DROP COLUMN IF EXISTS profile_photo")
        cursor.execute("ALTER TABLE students ADD COLUMN IF NOT EXISTS profile_photo_id UUID REFERENCES files(file_id) ON DELETE SET NULL")
        cursor.execute("CREATE INDEX IF NOT EXISTS students_profile_photo_id_idx ON students(profile_photo_id)")


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0043_alter_newadmission_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(convert_profile_photo_to_charfield, reverse_convert_profile_photo),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='student',
                    name='profile_photo',
                    field=models.CharField(blank=True, help_text='Profile photo URL or file path', max_length=100, null=True),
                ),
                migrations.AlterField(
                    model_name='teacher',
                    name='profile_photo',
                    field=models.CharField(blank=True, help_text='Profile photo URL or file path', max_length=100, null=True),
                ),
            ],
        ),
    ]
