# Generated by Django 4.2.7 on 2025-12-25 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0045_change_teacher_primary_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, help_text='Address', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', help_text='Department assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='management_admin.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_no',
            field=models.CharField(help_text='Employee number (unique identifier)', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(help_text='First name (required)', max_length=150),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Gender', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active status'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date of joining', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(blank=True, help_text='Mobile phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(blank=True, help_text='Educational qualifications', max_length=255, null=True),
        ),
    ]
