# Generated by Django 4.2.7 on 2025-12-30 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0046_remove_teacher_teacher_id_alter_teacher_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True)),
                ('name', models.CharField(help_text='Event name', max_length=255)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Administrative', 'Administrative'), ('Career', 'Career'), ('Other', 'Other')], default='Other', help_text='Event category', max_length=50)),
                ('date', models.DateField(help_text='Event date')),
                ('time', models.CharField(blank=True, help_text='Event time (e.g., 09:00 AM - 12:00 PM)', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Event location', max_length=255)),
                ('organizer', models.CharField(blank=True, help_text='Event organizer', max_length=255)),
                ('participants', models.IntegerField(default=0, help_text='Estimated number of participants', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed')], default='Upcoming', help_text='Event status', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
