# Generated by Django 4.2.7 on 2025-12-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0047_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Uploaded receipt file (PDF, image, etc.)', null=True, upload_to='receipts/'),
        ),
    ]
