# Generated by Django 4.2.7 on 2025-12-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0048_paymenthistory_receipt_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='receipt_file',
        ),
        migrations.AddField(
            model_name='fee',
            name='upload_receipt',
            field=models.CharField(blank=True, help_text='Uploaded receipt file path or URL', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='upload_receipt',
            field=models.CharField(blank=True, help_text='Uploaded receipt file path or URL', max_length=100, null=True),
        ),
    ]
