# Generated by Django 4.2.7 on 2025-12-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0013_fix_null_school_ids'),
        ('management_admin', '0048_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='course_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='department',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='head_name',
            field=models.CharField(blank=True, help_text='Name of the department head', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='school_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CampusFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('academic', 'Academic Facilities'), ('sports', 'Sports & Recreation'), ('technology', 'Technology & Labs'), ('arts', 'Arts & Culture'), ('infrastructure', 'Infrastructure'), ('amenities', 'Amenities'), ('speciality', 'Campus Speciality')], default='academic', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under-construction', 'Under Construction'), ('planned', 'Planned'), ('maintenance', 'Under Maintenance')], default='active', max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campus_features', to='super_admin.school')),
            ],
            options={
                'verbose_name': 'Campus Feature',
                'verbose_name_plural': 'Campus Features',
                'db_table': 'campus_features',
                'ordering': ['-date_added', '-created_at'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
