# Generated by Django 4.2.7 on 2025-12-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0049_add_upload_receipt_to_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Bus_route',
            field=models.CharField(blank=True, help_text='Bus route assigned to the student', max_length=100, null=True),
        ),
    ]
