# Generated by Django 4.2.7 on 2025-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0049_department_code_department_course_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('title', models.CharField(help_text='Event/Holiday title', max_length=255)),
                ('event_type', models.CharField(choices=[('Holiday', 'Holiday'), ('Academic', 'Academic Date (e.g., Term Start)'), ('Exam', 'Examination'), ('Event', 'School Event'), ('Meeting', 'Meeting'), ('Other', 'Other')], default='Event', max_length=50)),
                ('date', models.DateField(help_text='Date of the record')),
                ('end_date', models.DateField(blank=True, help_text='End date for multi-day events', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True, help_text='Display to students/parents')),
                ('color', models.CharField(blank=True, help_text='Hex color code for calendar display', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendar Record',
                'verbose_name_plural': 'Calendar Records',
                'db_table': 'calendar_records',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Cultural', 'Cultural'), ('Administrative', 'Administrative'), ('Career', 'Career'), ('Holiday', 'Holiday'), ('Exam', 'Exam'), ('Other', 'Other')], default='Other', help_text='Event category', max_length=50),
        ),
    ]
