# Generated by Django 4.2.7 on 2026-01-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0050_calendarrecord_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, help_text='Event end date', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Event end time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Event start time', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, help_text='Event time (Legacy field)', max_length=100),
        ),
    ]
