# Generated by Django 4.2.7 on 2025-12-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0050_student_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Bus_route',
        ),
    ]
