# Generated by Django 4.2.7 on 2026-01-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0049_department_code_department_course_count_and_more'),
        ('management_admin', '0051_remove_student_bus_route'),
    ]

    operations = [
    ]
