# Generated by Django 4.2.7 on 2026-01-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0052_merge_20260101_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
