# Generated by Django 4.2.7 on 2026-01-06 06:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0014_school_logo'),
        ('management_admin', '0012_galleryimage_caption_galleryimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={},
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, help_text='Relation with emergency contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, help_text='Experience details (e.g. 5 years)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary details', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='award',
            table=None,
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True)),
                ('name', models.CharField(help_text='Activity name', max_length=255)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Academic', 'Academic'), ('Arts', 'Arts'), ('Games', 'Games'), ('Cultural', 'Cultural'), ('Technical', 'Technical')], help_text='Activity category', max_length=50)),
                ('instructor', models.CharField(help_text='Instructor name', max_length=255)),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('schedule', models.CharField(help_text='Activity schedule (e.g., Monday, Wednesday 3:00 PM)', max_length=255)),
                ('location', models.CharField(help_text='Activity location', max_length=255)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Completed', 'Completed')], default='Active', help_text='Activity status', max_length=50)),
                ('start_date', models.DateField(blank=True, help_text='Activity start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Activity end date', null=True)),
                ('description', models.TextField(help_text='Detailed activity description')),
                ('requirements', models.TextField(blank=True, help_text='Requirements or prerequisites')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, related_name='school_activities', to='super_admin.school')),
            ],
            options={
                'verbose_name': 'School Activity',
                'verbose_name_plural': 'School Activities',
                'db_table': 'school_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
