# Generated by Django 4.2.7 on 2026-01-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0054_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, help_text='Relation with emergency contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, help_text='Years of experience', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary information', max_length=50, null=True),
        ),
    ]
