# Generated by Django 4.2.7 on 2026-01-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0054_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
