# Generated by Django 4.2.7 on 2026-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0055_alter_event_options_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Event start date and time', null=True),
        ),
    ]
