# Generated by Django 4.2.7 on 2026-01-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0054_alter_award_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='document',
            field=models.CharField(blank=True, help_text='Award document/certificate URL', max_length=255, null=True),
        ),
    ]
