# Generated by Django 4.2.7 on 2026-01-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0056_event_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Event end date and time', null=True),
        ),
    ]
