# Generated by Django 4.2.7 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0057_gallery_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='document',
            field=models.FileField(blank=True, help_text='Award document/certificate', null=True, upload_to='awards/certificates/'),
        ),
    ]
