# Generated by Django 4.2.7 on 2026-01-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0058_alter_award_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True, help_text='Other achievements', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='activities',
            field=models.TextField(blank=True, help_text='Extracurricular activities', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='leadership',
            field=models.TextField(blank=True, help_text='Leadership roles', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='participation',
            field=models.TextField(blank=True, help_text='Participation record', null=True),
        ),
    ]
