# Generated by Django 4.2.7 on 2026-01-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0059_student_achievements_student_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Leadership', 'Leadership'), ('Innovation', 'Innovation'), ('Community', 'Community'), ('Science Fair', 'Science Fair'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Other', 'Other')], default='Other', help_text='Award category', max_length=50),
        ),
    ]
