# Generated by Django 4.2.7 on 2026-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0061_delete_award'),
    ]

    operations = [
        migrations.RunSQL('DROP INDEX IF EXISTS awards_school_id_a334c924;'),
        migrations.RunSQL('DROP INDEX IF EXISTS awards_school_id_a334c924_like;'),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering', max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, editable=False, help_text='School name', max_length=255, null=True)),
                ('title', models.CharField(help_text='Award title', max_length=255)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Leadership', 'Leadership'), ('Innovation', 'Innovation'), ('Community', 'Community'), ('Science Fair', 'Science Fair'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Other', 'Other')], default='Other', help_text='Award category', max_length=50)),
                ('recipient', models.CharField(help_text='Recipient name', max_length=255)),
                ('student_ids', models.TextField(blank=True, help_text='Comma-separated student IDs (for team awards)')),
                ('date', models.DateField(help_text='Award date')),
                ('description', models.TextField(blank=True, help_text='Award description')),
                ('level', models.CharField(choices=[('School', 'School'), ('District', 'District'), ('State', 'State'), ('National', 'National'), ('International', 'International')], default='School', help_text='Award level', max_length=50)),
                ('presented_by', models.CharField(blank=True, help_text='Presented by (organization or person)', max_length=255)),
                ('document', models.FileField(blank=True, help_text='Award document/certificate', null=True, upload_to='awards/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
                'db_table': 'awards',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
