# Generated by Django 4.2.7 on 2026-01-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0062_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
