# Generated by Django 4.2.7 on 2026-01-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0063_remove_galleryimage_gallery_remove_activity_status_and_more'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE IF EXISTS gallery_images CASCADE;'),
        migrations.RunSQL('DROP TABLE IF EXISTS gallery CASCADE;'),
        migrations.RunSQL('ALTER TABLE school_activities DROP COLUMN IF EXISTS status;'),
        migrations.RunSQL('ALTER TABLE events DROP COLUMN IF EXISTS time;'),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering', max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, editable=False, help_text='School name', max_length=255, null=True)),
                ('title', models.CharField(help_text='Gallery title', max_length=255)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Academic', 'Academic'), ('Cultural', 'Cultural'), ('Awards', 'Awards'), ('Activities', 'Activities'), ('Other', 'Other')], default='Other', help_text='Event category', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description')),
                ('date', models.DateField(help_text='Event date')),
                ('photographer', models.CharField(blank=True, help_text='Photographer name', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Location', max_length=255)),
                ('emoji', models.CharField(blank=True, default='📷', help_text='Emoji icon', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'gallery',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Completed', 'Completed')], default='Active', help_text='Activity status', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, help_text='Event time (e.g., 09:00 AM - 12:00 PM)', max_length=100),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='Image URL or path', max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(help_text='Parent gallery', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='management_admin.gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'gallery_images',
            },
        ),
    ]
