# Generated by Django 4.2.7 on 2026-01-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0064_gallery_activity_status_event_time_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='award',
            name='document',
        ),
        migrations.RemoveField(
            model_name='student',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='student',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='student',
            name='leadership',
        ),
        migrations.RemoveField(
            model_name='student',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Leadership', 'Leadership'), ('Innovation', 'Innovation'), ('Community', 'Community'), ('Other', 'Other')], default='Other', help_text='Award category', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date'),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
