# Generated by Django 4.2.7 on 2026-01-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0064_gallery_activity_status_event_time_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Certificate image/document', upload_to='awards/certificates/')),
                ('student_id', models.CharField(blank=True, help_text='Optional: Specific student ID this document belongs to', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(help_text='Parent award', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='management_admin.award')),
            ],
            options={
                'verbose_name': 'Award Document',
                'verbose_name_plural': 'Award Documents',
                'db_table': 'award_documents',
            },
        ),
    ]
