# Generated by Django 4.2.7 on 2026-01-08 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0065_awarddocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwardDocument',
        ),
    ]
