# Generated by Django 4.2.7 on 2026-01-07 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0065_remove_galleryimage_gallery_remove_award_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering', max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, editable=False, help_text='School name', max_length=255, null=True)),
                ('title', models.CharField(help_text='Gallery title', max_length=255)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Academic', 'Academic'), ('Cultural', 'Cultural'), ('Awards', 'Awards'), ('Activities', 'Activities'), ('Other', 'Other')], default='Other', help_text='Event category', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description')),
                ('date', models.DateField(help_text='Event date')),
                ('photographer', models.CharField(blank=True, help_text='Photographer name', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Location', max_length=255)),
                ('emoji', models.CharField(blank=True, default='📷', help_text='Emoji icon', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'db_table': 'gallery',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='award',
            name='document',
            field=models.FileField(blank=True, help_text='Award document/certificate', null=True, upload_to='awards/certificates/'),
        ),
        migrations.AddField(
            model_name='student',
            name='achievements',
            field=models.TextField(blank=True, help_text='Other achievements', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='activities',
            field=models.TextField(blank=True, help_text='Extracurricular activities', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='leadership',
            field=models.TextField(blank=True, help_text='Leadership roles', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='participation',
            field=models.TextField(blank=True, help_text='Participation record', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, help_text='Relation with emergency contact', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, help_text='Years of experience', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary information', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Leadership', 'Leadership'), ('Innovation', 'Innovation'), ('Community', 'Community'), ('Science Fair', 'Science Fair'), ('NSS', 'NSS'), ('NCC', 'NCC'), ('Other', 'Other')], default='Other', help_text='Award category', max_length=50),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(help_text='Image URL or path', max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(help_text='Parent gallery', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='management_admin.gallery')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'gallery_images',
            },
        ),
    ]
