# Generated by Django 4.2.7 on 2026-01-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0066_gallery_award_document_student_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstopstudent',
            name='student_grade',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='newadmission',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher_grade',
        ),
        migrations.AddField(
            model_name='busstopstudent',
            name='student_section',
            field=models.CharField(blank=True, help_text='Student section (cached from student table)', max_length=50),
        ),
        migrations.AddField(
            model_name='fee',
            name='section',
            field=models.CharField(default='A', help_text='Section of the student (A, B, C, D)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newadmission',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Section of the student (A, B, C, or D)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, help_text='Section of the student', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_section',
            field=models.CharField(blank=True, help_text='Section for class teacher assignment (e.g., A, B, C, D)', max_length=10, null=True),
        ),
    ]
