# Generated by Django 4.2.7 on 2026-01-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0066_gallery_award_document_student_achievements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Event end date and time', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Event start date and time', null=True),
        ),
    ]
