# Generated by Django 4.2.7 on 2026-01-08 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0067_auto_20260108_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='team_id',
            field=models.CharField(blank=True, help_text='Import-time grouping ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='document',
            field=models.FileField(blank=True, help_text='Direct award document/certificate (legacy or single)', null=True, upload_to='awards/certificates/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, help_text='Event time (e.g., 09:00 AM - 12:00 PM)', max_length=100),
        ),
        migrations.CreateModel(
            name='AwardCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Certificate image/document', upload_to='awards/certificates/')),
                ('student_id', models.CharField(blank=True, help_text='Student ID this certificate belongs to', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(help_text='Parent award', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='management_admin.award')),
            ],
            options={
                'verbose_name': 'Award Certificate',
                'verbose_name_plural': 'Award Certificates',
                'db_table': 'award_certificates',
            },
        ),
    ]
