# Generated by Django 4.2.7 on 2026-01-09 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0067_alter_event_options_remove_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photo_id',
            field=models.CharField(blank=True, help_text='Gallery Photo ID (e.g., PID-123)', max_length=100),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.FileField(help_text='Gallery image (jpg/jpeg/png/gif only)', upload_to='gallery_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
