# Generated by Django 4.2.7 on 2026-01-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0068_gallery_photo_id_alter_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstopstudent',
            name='student_grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher_grade',
        ),
    ]
