# Generated by Django 4.2.7 on 2026-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0069_remove_busstopstudent_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstopstudent',
            name='student_grade',
            field=models.CharField(blank=True, help_text='Student grade (cached from student table)', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_grade',
            field=models.CharField(blank=True, help_text='Grade level for class teacher assignment (e.g., A, B, C, D)', max_length=10, null=True),
        ),
    ]
