# Generated by Django 4.2.7 on 2026-01-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0070_busstopstudent_student_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
    ]
