# Generated by Django 4.2.7 on 2026-01-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0072_event_end_datetime_event_start_datetime'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='newadmission',
                    name='grade',
                    field=models.CharField(blank=True, help_text='Section/Grade of the student', max_length=50, null=True),
                ),
            ],
        ),
    ]
