# Generated by Django 4.2.7 on 2026-01-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0073_alter_newadmission_grade'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='newadmission',
                    old_name='grade',
                    new_name='section',
                ),
                migrations.RemoveField(
                    model_name='student',
                    name='grade',
                ),
                migrations.AddField(
                    model_name='student',
                    name='section',
                    field=models.CharField(blank=True, help_text='Section/Grade of the student', max_length=50, null=True),
                ),
            ],
        ),
    ]
