# Generated by Django 4.2.7 on 2026-01-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0074_rename_grade_newadmission_section_and_more'),
    ]

    operations = [
        # Remove the old 'grade' columns since 'section' columns already exist
        migrations.RemoveField(
            model_name='busstopstudent',
            name='student_grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher_grade',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_class',
            field=models.CharField(blank=True, help_text='Class name for class teacher assignment (e.g., Nursery, 10, 12)', max_length=50, null=True),
        ),
    ]
