# Generated by Django 4.2.7 on 2026-01-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0075_rename_grade_to_section_all'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='fee',
        #     name='grade',
        # ),
        # migrations.AddField(
        #     model_name='busstopstudent',
        #     name='student_section',
        #     field=models.CharField(blank=True, help_text='Student section (cached from student table)', max_length=50),
        # ),
        # migrations.AddField(
        #     model_name='fee',
        #     name='section',
        #     field=models.CharField(blank=True, help_text='Section of the student (e.g., A, B, Lotus)', max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='teacher',
        #     name='class_teacher_section',
        #     field=models.CharField(blank=True, help_text='Section name for class teacher assignment (e.g., A, B, Lotus)', max_length=10, null=True),
        # ),
    ]
