# Generated by Django 4.2.7 on 2025-12-16 11:30

from django.db import migrations, models


def add_school_id_fields_if_not_exists(apps, schema_editor):
    """Add school_id fields only if they don't already exist"""
    db_alias = schema_editor.connection.alias
    
    # Check if tables exist before adding fields
    with schema_editor.connection.cursor() as cursor:
        # Get list of existing tables and columns
        cursor.execute("""
            SELECT table_name, column_name 
            FROM information_schema.columns 
            WHERE table_schema = 'public' 
            AND table_name IN ('communications', 'fees', 'notifications', 'parents')
        """)
        existing_columns = {(row[0], row[1]) for row in cursor.fetchall()}
        
        # Add fields only if they don't exist
        if ('communications', 'school_id') not in existing_columns:
            try:
                cursor.execute("""
                    ALTER TABLE communications 
                    ADD COLUMN school_id VARCHAR(100);
                    CREATE INDEX communications_school_id_idx ON communications(school_id);
                """)
            except Exception:
                pass  # Column might already exist
        
        if ('fees', 'school_id') not in existing_columns:
            try:
                cursor.execute("""
                    ALTER TABLE fees 
                    ADD COLUMN school_id VARCHAR(100);
                    CREATE INDEX fees_school_id_idx ON fees(school_id);
                """)
            except Exception:
                pass
        
        if ('notifications', 'school_id') not in existing_columns:
            try:
                cursor.execute("""
                    ALTER TABLE notifications 
                    ADD COLUMN school_id VARCHAR(100);
                    CREATE INDEX notifications_school_id_idx ON notifications(school_id);
                """)
            except Exception:
                pass
        
        if ('parents', 'school_id') not in existing_columns:
            try:
                cursor.execute("""
                    ALTER TABLE parents 
                    ADD COLUMN school_id VARCHAR(100);
                    CREATE INDEX parents_school_id_idx ON parents(school_id);
                """)
            except Exception:
                pass


def remove_school_id_fields(apps, schema_editor):
    """Remove school_id fields if they exist"""
    db_alias = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("ALTER TABLE communications DROP COLUMN IF EXISTS school_id;")
            cursor.execute("ALTER TABLE fees DROP COLUMN IF EXISTS school_id;")
            cursor.execute("ALTER TABLE notifications DROP COLUMN IF EXISTS school_id;")
            cursor.execute("ALTER TABLE parents DROP COLUMN IF EXISTS school_id;")
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0001_initial'),
    ]

    operations = [
        # Use RunPython to handle cases where tables might not exist and add columns to database
        migrations.RunPython(add_school_id_fields_if_not_exists, remove_school_id_fields),
        # Use SeparateDatabaseAndState to only update model state (columns already exist in DB)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations needed - columns already added by RunPython above
            ],
            state_operations=[
                # Update model state to reflect the fields that were added to the database
                migrations.AddField(
                    model_name='communication',
                    name='school_id',
                    field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='fee',
                    name='school_id',
                    field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='notification',
                    name='school_id',
                    field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='parent',
                    name='school_id',
                    field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
                ),
            ],
        ),
    ]
