# Generated by Django 4.2.7 on 2025-12-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0002_communication_school_id_fee_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
    ]
