# Generated by Django 4.2.7 on 2025-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0003_alter_communication_school_id_alter_fee_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
    ]
