# Generated by Django 4.2.7 on 2025-12-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0004_parent_school_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
    ]
