# Generated by Django 4.2.7 on 2025-12-25 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_parent', '0005_alter_parent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from users table)', max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('video', 'Video')], default='text', help_text='Type of message: text, image, file, or video', max_length=20)),
                ('message_text', models.TextField(blank=True, help_text='Text content of the message (required for text messages)', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Attached file, image, or video', null=True, upload_to='chat_attachments/%Y/%m/%d/')),
                ('attachment_name', models.CharField(blank=True, help_text='Original filename of the attachment', max_length=255, null=True)),
                ('attachment_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('attachment_type', models.CharField(blank=True, help_text='MIME type of the attachment (e.g., image/jpeg, application/pdf)', max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the recipient has read this message')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the message was read', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag - message is marked as deleted but kept in database')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the message was deleted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='User who receives the message', on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', 'created_at'], name='chat_messag_sender__9d0045_idx'), models.Index(fields=['school_id', 'created_at'], name='chat_messag_school__8d47c6_idx'), models.Index(fields=['is_read', 'created_at'], name='chat_messag_is_read_d4ca25_idx')],
            },
        ),
    ]
