# Generated by Django 4.2.7 on 2025-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0003_add_school_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(help_text='Unique school identifier (Primary Key)', max_length=100, primary_key=True, serialize=False),
        ),
    ]
