# Generated by Django 4.2.7 on 2025-12-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0007_make_activity_school_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(editable=False, help_text='Auto-generated school identifier (Primary Key) - Format: state_district_registration_number', max_length=200, primary_key=True, serialize=False),
        ),
    ]
