# Generated by Django 4.2.7 on 2025-12-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0009_rename_state_district_to_statecode_districtcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(editable=False, help_text='Auto-generated school identifier (Primary Key) - Format: StateCode + DistrictCode + RegistrationNumber', max_length=200, primary_key=True, serialize=False),
        ),
    ]
