# Generated by Django 4.2.7 on 2025-12-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0010_alter_school_school_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='school_name',
        ),
    ]
