# Generated by Django 4.2.7 on 2025-12-23 05:36

from django.db import migrations


def populate_school_name_in_all_tables(apps, schema_editor):
    """Populate school_name field in all tables that have it"""
    # Get School model to build the mapping
    School = apps.get_model('super_admin', 'School')
    
    # Create a mapping of school_id to school_name for faster lookups
    school_name_map = {}
    for school in School.objects.all():
        school_name_map[school.school_id] = school.school_name
    
    # Update Teachers using raw SQL to avoid field mismatch issues
    print("Updating school_name in teachers table...")
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE teachers SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
    
    # Update all other tables using raw SQL to avoid field mismatch issues
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Update Students
        print("Updating school_name in students table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE students SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Parents
        print("Updating school_name in parents table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE parents SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Files
        print("Updating school_name in files table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE files SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Fees
        print("Updating school_name in fees table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE fees SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update BusStops
        print("Updating school_name in bus_stops table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE bus_stops SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update BusStopStudents
        print("Updating school_name in bus_stop_students table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE bus_stop_students SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Classes
        print("Updating school_name in classes table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE classes SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update ClassStudents
        print("Updating school_name in class_students table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE class_students SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Attendances
        print("Updating school_name in attendances table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE attendances SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Assignments
        print("Updating school_name in assignments table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE assignments SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Exams
        print("Updating school_name in exams table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE exams SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Grades
        print("Updating school_name in grades table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE grades SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update Timetables
        print("Updating school_name in timetables table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE timetables SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update StudyMaterials
        print("Updating school_name in study_materials table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE study_materials SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
        
        # Update ExaminationManagement
        print("Updating school_name in examination_management table...")
        for school_id, school_name in school_name_map.items():
            cursor.execute(
                "UPDATE examination_management SET school_name = %s WHERE school_id = %s",
                [school_name, school_id]
            )
    
    print("Finished populating school_name in all tables!")


def reverse_populate_school_name(apps, schema_editor):
    """Reverse migration - clear school_name fields"""
    # This is a one-way migration, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0011_rename_name_to_school_name'),
        ('management_admin', '0041_busstop_school_name_busstopstudent_school_name_and_more'),
        ('student_parent', '0004_parent_school_name'),
        ('teacher', '0004_assignment_school_name_attendance_school_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_school_name_in_all_tables, reverse_populate_school_name),
    ]
