# Generated by Django 4.2.7 on 2025-12-23

from django.db import migrations


def fix_null_school_ids(apps, schema_editor):
    """Fix any schools with null or empty school_id"""
    School = apps.get_model('super_admin', 'School')
    
    # Find all schools with null, empty, or missing school_id
    schools_to_fix = School.objects.filter(
        school_id__isnull=True
    ) | School.objects.filter(
        school_id=''
    )
    
    fixed_count = 0
    skipped_count = 0
    
    for school in schools_to_fix:
        # Check if required fields are present
        statecode = (school.statecode or '').strip()
        districtcode = (school.districtcode or '').strip()
        registration_number = (school.registration_number or '').strip()
        
        if statecode and districtcode and registration_number:
            # Generate school_id
            state_normalized = statecode.upper().replace(' ', '')
            district_normalized = districtcode.upper().replace(' ', '')
            reg_normalized = registration_number.upper().replace(' ', '')
            school_id = f"{state_normalized}{district_normalized}{reg_normalized}"
            
            # Check if this school_id already exists
            if School.objects.filter(school_id=school_id).exclude(pk=school.pk if hasattr(school, 'pk') and school.pk else None).exists():
                print(f"Skipping school {school.school_name}: school_id '{school_id}' already exists")
                skipped_count += 1
                continue
            
            # Update the school_id
            school.school_id = school_id
            school.save(update_fields=['school_id'])
            fixed_count += 1
            print(f"Fixed school_id for school: {school.school_name} -> {school_id}")
        else:
            print(f"Skipping school {school.school_name}: Missing required fields (statecode, districtcode, or registration_number)")
            skipped_count += 1
    
    print(f"Fixed {fixed_count} schools, skipped {skipped_count} schools")


def reverse_fix(apps, schema_editor):
    """Reverse migration - cannot reverse this operation"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0012_populate_school_name_in_all_tables'),
    ]

    operations = [
        migrations.RunPython(fix_null_school_ids, reverse_fix),
    ]
