# Generated by Django 4.2.7 on 2026-01-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, help_text='School logo image', null=True, upload_to='school_logos/'),
        ),
    ]
