# Generated by Django 4.2.7 on 2026-01-13 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDetails',
            fields=[
                ('financial_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(help_text='Hashed password', max_length=255)),
                ('full_name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('school_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Detail',
                'verbose_name_plural': 'Financial Details',
                'db_table': 'financial_details',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('management_admin', 'Management Admin'), ('teacher', 'Teacher'), ('student_parent', 'Student/Parent'), ('financial', 'Financial Staff')], max_length=50, unique=True),
        ),
    ]
