# Generated by Django 4.2.7 on 2025-12-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, help_text='Temporary login 8-character password', max_length=8, null=True),
        ),
    ]
