# Generated by Django 4.2.7 on 2025-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0004_alter_user_updated_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, auto-populated from related models)', max_length=100, null=True),
        ),
    ]
