# Generated by Django 4.2.7 on 2026-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0004_financialdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdetails',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
