# Generated by Django 4.2.7 on 2026-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_otp',
            field=models.CharField(blank=True, help_text='OTP for password reset', max_length=6, null=True),
        ),
    ]
