# Generated by Django 4.2.7 on 2026-01-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, help_text="Teacher's remarks for this attendance record", null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(blank=True, help_text='Snapshot of student name at time of marking', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Snapshot of teacher name at time of marking', max_length=255, null=True),
        ),
    ]
