# Generated by Django 4.2.7 on 2025-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, help_text='School ID for filtering', max_length=100, null=True),
        ),
    ]
