# Generated by Django 4.2.7 on 2025-12-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assignment_school_id_attendance_school_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classstudent',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='school_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='School ID for filtering (read-only, fetched from schools table)', max_length=100, null=True),
        ),
    ]
