# Generated by Django 4.2.7 on 2026-01-14 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_project_task_studentproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='teacher.class'),
        ),
        migrations.AlterField(
            model_name='task',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teacher.class'),
        ),
    ]
