# Generated by Django 4.2.7 on 2026-01-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_exam_duration_minutes_exam_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(blank=True, choices=[('Homework', 'Homework'), ('Project', 'Project'), ('Lab', 'Lab'), ('Other', 'Other')], default='Homework', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions for the assignment'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
