# Generated by Django 4.2.7 on 2025-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_assignment_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classstudent',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school_name',
            field=models.CharField(blank=True, editable=False, help_text='School name (read-only, auto-populated from schools table)', max_length=255, null=True),
        ),
    ]
