# Generated by Django 4.2.7 on 2026-01-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0068_gallery_photo_id_alter_galleryimage_image'),
        ('teacher', '0004_assignment_assignment_type_assignment_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='color',
            field=models.CharField(default='#667EEA', help_text='Color code for the subject (hex format)', max_length=7),
        ),
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.CharField(blank=True, help_text='Room number or location', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='management_admin.teacher'),
        ),
    ]
